# Generated by Django 5.1.7 on 2025-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='envelope_sender_full',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
