# Generated by Django 5.1.7 on 2025-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailtemplate_envelope_sender_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
