# Generated by Django 5.1.7 on 2025-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_emailtemplate_body_emailtemplate_html_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
