# Generated by Django 5.1.7 on 2025-03-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_envelope_sender_full_emailtemplate_envelope_sender_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
