# Generated by Django 5.1.7 on 2025-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_landingpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
