# Generated by Django 4.2.18 on 2025-04-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_landingpage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailtemplate'),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='groups',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.landingpage'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sending_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sendingprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.group'),
        ),
    ]
