# Generated by Django 4.2.18 on 2025-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_campaign_email_template_remove_campaign_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
